--- 
clone: 
  depth: 1
kind: pipeline
name: AzurePipeline
steps: 
  - 
    commands: 
      - "export token=$TOKEN"
      - "curl https://raw.githubusercontent.com/Panchajanya1999/myscripts/master/kernel.sh | bash"
    environment: 
      TOKEN: 
        from_secret: token
    image: panchajanya1999/archlinux:latest
    name: Azure-Images
    trigger: 
      branch: 
        - LTO
        - Q
        - test
